# Generated by Django 3.1.2 on 2020-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201120_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
